# -------------------------
# Model
# -------------------------
model_name_or_path: "Qwen/Qwen2.5-1.5B-Instruct"  # Path or HF repo ID

# -------------------------
# Dataset / Files
# -------------------------
output_dir: "llmsql_finetune_outputs2/finetuned-llama"

# -------------------------
# Training hyperparameters
# -------------------------
shots: 1
num_train_epochs: 3
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
learning_rate: !!float 5e-5
save_steps: 100
logging_steps: 1
seed: 42

no_eval: false
eval_steps: 100
max_length: 2048

# -------------------------
# Misc / Logging
# -------------------------
wandb:
  project: ""
  run_name: ""
  key: ""
  offline: false
