name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # adjust if you need a different version

      - name: Install PDM
        run: pip install pdm

      - name: Cache PDM packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pdm
          key: ${{ runner.os }}-pdm-${{ hashFiles('pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pdm-

      - name: Install dependencies (with dev)
        run: pdm install --with dev

      - name: Run tests
        run: PYTHONPATH=. pdm run pytest -v --maxfail=1 --disable-warnings
