name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PDM
        run: pip install pdm

      - name: Cache PDM packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pdm
          key: ${{ runner.os }}-pdm-${{ hashFiles('pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pdm-

      - name: Install dependencies (with dev)
        run: pdm install --with dev

      - name: Run tests with coverage
        run: PYTHONPATH=. pdm run pytest --cov=llmsql --cov-report=xml --maxfail=1 --disable-warnings -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
